package exceptions;

import col.Employee;

public class ExceptionEx {
	private Employee employee;
	
	public static void main(String[] args) {
		ExceptionEx ex= new Exception();
		ex.execute();
		System.out.println("after execute in main");
	}
	
	public void execute() {
		try {
			int id = employee.getId();
			System.out.println("after handling Exception");
		}catch( Exception e) {
			e.printStackTrace();
			System.out.println("handled Exception");
		}
	}
}
